- shell:
    - description: installing st, the suckless terminal
      quiet: true
      command: |-
       git -C st submodule sync --quiet --recursive
       git submodule update --init --recursive st

       cd st
       make install
