- create:
    - ~/.local/share/yakuake/kns_skins

- shell:
    - description: Syncing Yakuake Themes
      quiet: true
      command: |-
        git -C themes submodule sync --quiet --recursive
        git submodule update --init --recursive themes

- link:
    ~/.config/yakuakerc:
    ~/.local/share/yakuake/kns_skins/an-old-hope:
      path: themes/an-old-hope/an-old-hope

