- shell:
    - description: syncing fzf-tmux
      quiet: true
      command: |-
        if [ -e ./fzf-tmux ]; then
            :
        elif which fzf-tmux >/dev/null 2>/dev/null; then
            ln -s "$(which fzf-tmux)" ./fzf-tmux
        else
            if curl -LO https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux; then
                chmod +x ./fzf-tmux
            else
                echo "unable to retrieve fzf-tmux"
                exit 1
            fi
        fi

- link:
    ~/.config/tmux/scripts/attach-session:
    ~/.config/tmux/scripts/manage-windows:
    ~/.config/tmux/scripts/run-binding:
    ~/.config/tmux/scripts/run-command:
    ~/programming/scripts/fzf-tmux:
        path: fzf-tmux
        force: true
        ignore-missing: true
