- link:
    ~/.gemrc:
    ~/.config/irb/irbrc:
    ~/.config/pry/pryrc:

- packages:
    - apt: ruby-full
    - chocolatey:
        - package: ruby
          # setup the ruby installer developement kit (ridk).
          # literally the only thing making ruby development on
          # windows not maddening.
          after: |-
              powershell -c '
                Set-ExecutionPolicy Bypass -Scope Process
                c:/tools/ruby27/bin/ridk.ps1 install 2 3'
    - pacman: ruby

- packages:
    - gem:
        - colorize
        - rake
