- link:
    ~/.Xresources:
    ~/.config/xbindkeys/config:
        path: xbindkeysrc
        create: true

- packages:
    pacman:
      - xorg
      - xorg-xinit
      - xbindkeys
      - wmctrl
      - xdotool

- shell:
    - description: Installing Graphics Drivers for Xorg
      quiet: true
      command: |-
        graphics_card=$(lspci | grep -e VGA -e 3D |
          rev | cut -d: -f1 | rev |
          sed -e 's/^ *//' -e 's/ *$//' |
          tr '[:upper:]' '[:lower:]')

        case "$graphics_card" in
          *intel*)
            sudo pacman -S --needed --noconfirm xf86-video-intel
            ;;
          *vmware*)
            sudo pacman -S --needed --noconfirm xf86-video-vmware
            ;;
          *)
            echo "unable to determine graphics card: $graphics_card" >&2
            ;;
        esac
