- shell:
    - description: Installing Chocolatey
      quiet: true
      command: |-
        choco_path=$(which choco 2>/dev/null)
        if [ -x "$choco_path" ]; then
          exit 0
        fi

        install_script='https://chocolatey.org/install.ps1'
        install_file=$(basename "$install_script")
        if ! [ -f "$install_file" ]; then
          curl -LO "$install_script" || exit 1
        fi

        powershell -Command '
          Set-ExecutionPolicy Bypass -Scope Process
          . ./'"$install_file"
